@include('admin.layout.head')
<div class="layuimini-container"><form id="app-form" class="layui-form layuimini-form layui-form-pane">
<div class="layui-form-item"><label class="layui-form-label">上级栏目</label><div class="layui-input-block"><select name="pid">@foreach($pidChannelList as $vo)<option value="{{$vo['id']}}">{!! $vo['title'] !!}</option>@endforeach</select></div></div>
<div class="layui-form-item"><label class="layui-form-label">栏目名称</label><div class="layui-input-block"><input type="text" name="title" lay-verify="required" class="layui-input"></div></div>
<div class="layui-form-item"><label class="layui-form-label">栏目别名</label><div class="layui-input-block"><input type="text" name="slug" class="layui-input" placeholder="如 about-us"></div></div>
<div class="layui-form-item"><label class="layui-form-label">栏目类型</label><div class="layui-input-block">@foreach($channelTypes as $key=>$val)<input type="radio" name="type" value="{{$key}}" title="{{$val}}" @if($key==='single') checked @endif>@endforeach</div></div>
<div class="layui-form-item"><label class="layui-form-label">封面</label><div class="layui-input-block layuimini-upload"><input name="cover" class="layui-input layui-col-xs6"><div class="layuimini-upload-btn"><span><a class="layui-btn" data-upload="cover" data-upload-number="one" data-upload-exts="png|jpg|jpeg" data-upload-icon="image"><i class="fa fa-upload"></i> 上传</a></span><span><a class="layui-btn layui-btn-normal" data-upload-select="cover" data-upload-number="one" data-upload-mimetype="image/*"><i class="fa fa-list"></i> 选择</a></span></div></div></div>
<div class="layui-form-item"><label class="layui-form-label">横幅</label><div class="layui-input-block layuimini-upload"><input name="banner" class="layui-input layui-col-xs6"><div class="layuimini-upload-btn"><span><a class="layui-btn" data-upload="banner" data-upload-number="one" data-upload-exts="png|jpg|jpeg" data-upload-icon="image"><i class="fa fa-upload"></i> 上传</a></span><span><a class="layui-btn layui-btn-normal" data-upload-select="banner" data-upload-number="one" data-upload-mimetype="image/*"><i class="fa fa-list"></i> 选择</a></span></div></div></div>
<div class="layui-form-item layui-form-text"><label class="layui-form-label">简介</label><div class="layui-input-block"><textarea name="summary" class="layui-textarea"></textarea></div></div>
<div class="layui-form-item"><label class="layui-form-label">导航显示</label><div class="layui-input-block"><input type="radio" name="is_nav" value="1" title="是" checked><input type="radio" name="is_nav" value="0" title="否"></div></div>
<div class="layui-form-item"><label class="layui-form-label">首页推荐</label><div class="layui-input-block"><input type="radio" name="is_index" value="1" title="是"><input type="radio" name="is_index" value="0" title="否" checked></div></div>
<div class="layui-form-item"><label class="layui-form-label">排序</label><div class="layui-input-block"><input type="number" name="sort" class="layui-input" value="0"></div></div>
<div class="layui-form-item"><label class="layui-form-label">SEO标题</label><div class="layui-input-block"><input type="text" name="seo_title" class="layui-input"></div></div>
<div class="layui-form-item"><label class="layui-form-label">SEO关键词</label><div class="layui-input-block"><input type="text" name="seo_keywords" class="layui-input"></div></div>
<div class="layui-form-item layui-form-text"><label class="layui-form-label">SEO描述</label><div class="layui-input-block"><textarea name="seo_description" class="layui-textarea"></textarea></div></div>
<div class="layui-form-item"><label class="layui-form-label">单页内容</label><div class="layui-input-block">{!! editor_textarea('', 'content') !!}</div></div>
<div class="hr-line"></div><div class="layui-form-item text-center"><button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button><button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button></div></form></div>
@include('admin.layout.foot')