<form id="app-form" class="layui-form layuimini-form">
    <div class="layui-form-item"><label class="layui-form-label">品牌名称</label><div class="layui-input-block"><input type="text" name="brand_name" class="layui-input" value="{{ sysconfig('website','brand_name') }}"></div></div>
    <div class="layui-form-item"><label class="layui-form-label">前台LOGO</label><div class="layui-input-block layuimini-upload"><input name="logo" class="layui-input layui-col-xs6" value="{{ sysconfig('website','logo') }}"><div class="layuimini-upload-btn"><span><a class="layui-btn" data-upload="logo" data-upload-number="one" data-upload-exts="png|jpg|jpeg|ico" data-upload-icon="image"><i class="fa fa-upload"></i> 上传</a></span><span><a class="layui-btn layui-btn-normal" data-upload-select="logo" data-upload-number="one" data-upload-mimetype="image/*"><i class="fa fa-list"></i> 选择</a></span></div></div></div>
    <div class="layui-form-item layui-form-text"><label class="layui-form-label">站点标语</label><div class="layui-input-block"><textarea name="tagline" class="layui-textarea">{{ sysconfig('website','tagline') }}</textarea></div></div>
    <div class="layui-form-item"><label class="layui-form-label">联系电话</label><div class="layui-input-block"><input type="text" name="service_phone" class="layui-input" value="{{ sysconfig('website','service_phone') }}"></div></div>
    <div class="layui-form-item"><label class="layui-form-label">联系邮箱</label><div class="layui-input-block"><input type="text" name="service_email" class="layui-input" value="{{ sysconfig('website','service_email') }}"></div></div>
    <div class="layui-form-item"><label class="layui-form-label">联系地址</label><div class="layui-input-block"><input type="text" name="company_address" class="layui-input" value="{{ sysconfig('website','company_address') }}"></div></div>
    <div class="layui-form-item"><label class="layui-form-label">工作时间</label><div class="layui-input-block"><input type="text" name="work_time" class="layui-input" value="{{ sysconfig('website','work_time') }}"></div></div>
    <div class="layui-form-item"><label class="layui-form-label">搜索提示</label><div class="layui-input-block"><input type="text" name="search_tip" class="layui-input" value="{{ sysconfig('website','search_tip') }}"></div></div>
    <div class="layui-form-item"><label class="layui-form-label">首页标题</label><div class="layui-input-block"><input type="text" name="hero_title" class="layui-input" value="{{ sysconfig('website','hero_title') }}"></div></div>
    <div class="layui-form-item layui-form-text"><label class="layui-form-label">首页摘要</label><div class="layui-input-block"><textarea name="hero_summary" class="layui-textarea">{{ sysconfig('website','hero_summary') }}</textarea></div></div>
    <div class="layui-form-item"><label class="layui-form-label">SEO 标题</label><div class="layui-input-block"><input type="text" name="seo_title" class="layui-input" value="{{ sysconfig('website','seo_title') }}"></div></div>
    <div class="layui-form-item"><label class="layui-form-label">SEO 关键词</label><div class="layui-input-block"><input type="text" name="seo_keywords" class="layui-input" value="{{ sysconfig('website','seo_keywords') }}"></div></div>
    <div class="layui-form-item layui-form-text"><label class="layui-form-label">SEO 描述</label><div class="layui-input-block"><textarea name="seo_description" class="layui-textarea">{{ sysconfig('website','seo_description') }}</textarea></div></div>
    <div class="hr-line"></div><div class="layui-form-item text-center"><button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit="website/config/save" data-refresh="false">确认</button><button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button></div>
</form>
