@include('admin.layout.head')
<div class="layuimini-container">
    <form id="app-form" class="layui-form layuimini-form layui-form-pane">
        <div class="layui-form-item"><label class="layui-form-label">产品分类</label><div class="layui-input-block"><select name="category_id">@foreach($categories as $key=>$val)<option value="{{$key}}" @selected($key==$row->category_id)>{{$val}}</option>@endforeach</select></div></div>
        <div class="layui-form-item"><label class="layui-form-label">产品名称</label><div class="layui-input-block"><input type="text" name="title" lay-verify="required" class="layui-input" value="{{$row->title??''}}"></div></div>
        <div class="layui-form-item"><label class="layui-form-label">别名</label><div class="layui-input-block"><input type="text" name="slug" class="layui-input" value="{{$row->slug??''}}"></div></div>
        <div class="layui-form-item"><label class="layui-form-label">型号</label><div class="layui-input-block"><input type="text" name="model_no" class="layui-input" value="{{$row->model_no??''}}"></div></div>
        <div class="layui-form-item"><label class="layui-form-label">封面</label><div class="layui-input-block layuimini-upload"><input name="cover" class="layui-input layui-col-xs6" value="{{$row->cover??''}}"><div class="layuimini-upload-btn"><span><a class="layui-btn" data-upload="cover" data-upload-number="one" data-upload-exts="png|jpg|jpeg" data-upload-icon="image"><i class="fa fa-upload"></i> 上传</a></span><span><a class="layui-btn layui-btn-normal" data-upload-select="cover" data-upload-number="one" data-upload-mimetype="image/*"><i class="fa fa-list"></i> 选择</a></span></div></div></div>
        <div class="layui-form-item"><label class="layui-form-label">图库</label><div class="layui-input-block layuimini-upload"><input name="gallery" class="layui-input layui-col-xs6" value="{{$row->gallery??''}}"><div class="layuimini-upload-btn"><span><a class="layui-btn" data-upload="gallery" data-upload-number="more" data-upload-exts="png|jpg|jpeg" data-upload-icon="image"><i class="fa fa-upload"></i> 上传</a></span><span><a class="layui-btn layui-btn-normal" data-upload-select="gallery" data-upload-number="more" data-upload-mimetype="image/*"><i class="fa fa-list"></i> 选择</a></span></div></div></div>
        <div class="layui-form-item layui-form-text"><label class="layui-form-label">摘要</label><div class="layui-input-block"><textarea name="summary" class="layui-textarea">{{$row->summary??''}}</textarea></div></div>
        <div class="layui-form-item layui-form-text"><label class="layui-form-label">参数</label><div class="layui-input-block"><textarea name="parameters" class="layui-textarea">{{$row->parameters??''}}</textarea></div></div>
        <div class="layui-form-item"><label class="layui-form-label">下载地址</label><div class="layui-input-block"><input type="text" name="download_url" class="layui-input" value="{{$row->download_url??''}}"></div></div>
        <div class="layui-form-item"><label class="layui-form-label">特色产品</label><div class="layui-input-block"><input type="radio" name="is_featured" value="1" title="是" @checked($row->is_featured==1)><input type="radio" name="is_featured" value="0" title="否" @checked($row->is_featured!=1)></div></div>
        <div class="layui-form-item"><label class="layui-form-label">上新产品</label><div class="layui-input-block"><input type="radio" name="is_new" value="1" title="是" @checked($row->is_new==1)><input type="radio" name="is_new" value="0" title="否" @checked($row->is_new!=1)></div></div>
        <div class="layui-form-item"><label class="layui-form-label">排序</label><div class="layui-input-block"><input type="number" name="sort" class="layui-input" value="{{$row->sort??0}}"></div></div>
        <div class="layui-form-item"><label class="layui-form-label">SEO标题</label><div class="layui-input-block"><input type="text" name="seo_title" class="layui-input" value="{{$row->seo_title??''}}"></div></div>
        <div class="layui-form-item"><label class="layui-form-label">SEO关键词</label><div class="layui-input-block"><input type="text" name="seo_keywords" class="layui-input" value="{{$row->seo_keywords??''}}"></div></div>
        <div class="layui-form-item layui-form-text"><label class="layui-form-label">SEO描述</label><div class="layui-input-block"><textarea name="seo_description" class="layui-textarea">{{$row->seo_description??''}}</textarea></div></div>
        <div class="layui-form-item"><label class="layui-form-label">产品详情</label><div class="layui-input-block">{!! editor_textarea($row->content ?? '', 'content') !!}</div></div>
        <div class="hr-line"></div><div class="layui-form-item text-center"><button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button><button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button></div>
    </form>
</div>
@include('admin.layout.foot')
